### ISSUE TITLE
Tool built on top of OpenAPI specification

### ISSUE THREAD

**Issue by reedelk** [oai-demandgen/home#15]
Hi,

Reedelk Open Source Data Integration Platform provides a tool to generate OpenAPI specification from Integration Flows exposing REST services but also generating blueprint starting from an imported OpenAPI specification:

Reedelk https://www.reedelk.com - https://twitter.com/reedelk - https://github.com/reedelk

Best,
Lorenzo

**Comment by kinlane** [comment]
You nailed what I am looking for Lorenzo. Thanks for adding your company. I will get you added to the list, and will start tuning into your projects to see how we can best amplify the great work you are doing. Please let us know any ideas on how we can help amplify what you are up to.

**Comment by kinlane** [comment]
I am going to close out this issue, as I've opened up to for helping showcase what Reedelk is building:

- **[Service Provider](https://github.com/oai-demandgen/service-providers/issues/3)** - The commercial services.
- **[Tooling](https://github.com/oai-demandgen/tools/issues/2)** - Just the open source tools.
